# Generated by Django 4.1.7 on 2023-02-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="isHome",
            field=models.BooleanField(default=True),
        ),
    ]
