# Generated by Django 4.1.7 on 2023-02-22 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                blank=True, default=uuid.uuid1, editable=False, unique=True
            ),
        ),
    ]
